plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

android {
    namespace 'com.waray.spendhound'
    compileSdk 34

    dataBinding {
        enabled = true
    }

    defaultConfig {
        applicationId "com.waray.spendhound"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation(platform("io.github.jan-tennert.supabase:bom:2.6.0"))
    implementation("io.github.jan-tennert.supabase:gotrue-kt")   // Auth
    implementation("io.github.jan-tennert.supabase:postgrest-kt")
    implementation("io.github.jan-tennert.supabase:realtime-kt")
    implementation("io.github.jan-tennert.supabase:storage-kt")
    implementation("io.ktor:ktor-client-android:2.3.5")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.3")

    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.navigation:navigation-runtime-ktx:2.7.1'
    implementation 'androidx.navigation:navigation-ui-ktx:2.7.1'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    // RecyclerView
    implementation 'androidx.recyclerview:recyclerview:1.3.1'

    // CardView
    implementation 'androidx.cardview:cardview:1.0.0'

    // ViewModel and LiveData
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.6.1'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.6.1'

    // Coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'

    // Gson
    implementation 'com.google.code.gson:gson:2.9.0'

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'

    // Glide
    implementation 'com.github.bumptech.glide:glide:4.12.0'
    implementation 'com.google.android.gms:play-services-auth:20.7.0'
    implementation 'com.google.firebase:firebase-storage:20.2.1'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.12.0'

    // Firebase Authentication (Keeping for reference or removal if fully replaced)
    // implementation 'com.google.firebase:firebase-auth:22.1.1'

    // Firebase Authentication (Keeping for reference or removal if fully replaced)
    // implementation 'com.google.firebase:firebase-auth:22.1.1'

    // Firebase Authentication (Keeping for reference or removal if fully replaced)
    // implementation 'com.google.firebase:firebase-auth:22.1.1'

    // Firebase Realtime Database
    implementation 'com.google.firebase:firebase-database:20.2.2'

    // Firebase Cloud Messaging
    implementation 'com.google.firebase:firebase-messaging:23.2.1'

    implementation platform('com.google.firebase:firebase-bom:32.1.1')
    implementation 'com.google.firebase:firebase-analytics'

    // Biometric
    implementation 'androidx.biometric:biometric:1.2.0-alpha05'
    implementation 'androidx.security:security-crypto:1.1.0-alpha06'

    // Room
    implementation 'androidx.room:room-runtime:2.5.2'
    annotationProcessor 'androidx.room:room-compiler:2.5.2'

    // MPAndroidChart for line graphs
    implementation 'com.github.PhilJay:MPAndroidChart:v3.1.0'

    // Add the dependencies for the Crashlytics and Analytics libraries
    implementation("com.google.firebase:firebase-crashlytics")
    implementation("com.google.firebase:firebase-analytics")
}
