package com.waray.spendhound

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Data model for the 'users' table.
 * If user_id is int8 in Supabase, we should let the DB generate it
 * and use a separate field for the Auth UID, OR change user_id to text/uuid.
 */
@Serializable
data class User(
    @SerialName("user_id")
    val id: Long? = null, // Numeric ID (Auto-generated by DB)
    @SerialName("auth_id")
    val authId: String? = null, // Link to Supabase Auth UID
    val username: String? = null,
    val email: String? = null,
    val password: String? = null,
    @SerialName("profile_image_url")
    val profileImageUrl: String? = null,
    @SerialName("total_bill_spent")
    val totalBillSpent: Double? = 0.0,
    @SerialName("total_bill_payment")
    val totalBillPayment: Double? = 0.0,
    @SerialName("total_receivable")
    val totalReceivable: Double? = 0.0,
    @SerialName("total_debt")
    val totalDebt: Double? = 0.0,
    @SerialName("total_individual_spent")
    val totalIndividualSpent: Double? = 0.0,
    @SerialName("created_at")
    val createdAt: String? = null
)
